### ISSUE TITLE
Email not visible

### ISSUE THREAD

**Issue by inferno1727** [Zyepher/Zefort#3]
The email is not visible when the question is two long/takes more then one line
![image0](https://user-images.githubusercontent.com/49772768/59716812-44707780-9249-11e9-874d-4dc5e17411ab.png)

**Comment by Zyepher** [comment]
This bug has been resolved temporarily by increasing the height of the message content. This is not an ideal solution, but I am unable to figure out how to automatically adjust the height based on the length of the message content.
